### ISSUE TITLE
Initial Implementation

### ISSUE THREAD

**Issue by antoniobeyah** [beyahsolutions/aws-assume-role-plugin#1]
Initially, the plugin should accept a text parameter with a role name and attempt to assume it using the instance role.  

These inputs should be supported (see [API_AssumeRole](http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html)):
- Duration
- ExternalId
- RoleSessionName
- RoleArn

The plugin should provide the following environment variables:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_SESSION_TOKEN

**Tasks**
- [ ] Wrapper that assumes the role
- [ ] Jenkins Job DSL support
- [ ] Jenkins Pipeline DSL support
- [ ] Write README explaining how to configure the roles

Out of scope for initial release (may be included in a future release):
- Support for using access keys to assume a role
- Listing/filtering of roles
